export default {
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  profileContainer: {
    flexDirection: 'row',
    height: '20%',
    marginTop: 50,
  },
  profileInner: {
    flex: 3,
  },
  userNameContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
  },
  userNameText: {
    fontWeight: 'bold',
    fontSize: 27,
  },
  followerContainer: {
    flexDirection: 'row',
    marginLeft: 20,
    marginTop: 15,
  },
  profileImageContainer: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  decriptionContainer: {
    justifyContent: 'space-around',
    flexDirection: 'column',
    paddingRight: 50,
    paddingLeft: 20,
    paddingBottom: 20,
    height: '8%',
    backgroundColor: '',
  },
  descriptionText: {
    fontSize: 15,
    fontWeight: '600',
  },
  tabs: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    padding: 3,
    height: 45,
    marginLeft: 20,
    marginRight: 20,
    backgroundColor: '#f1f1f1',
    borderRadius: 7,
  },
  folloBtn: {
    backgroundColor: '#fff',
    alignItems: 'center',
    paddingTop: 10,
    flex: 2,
    borderRadius: 5,
    marginRight: 5,
  },
  messageBtn: {
    backgroundColor: 'trans',
    alignItems: 'center',
    paddingTop: 10,
    flex: 2,
    borderRadius: 5,
    marginRight: 5,
  },
  tabContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    height: 45,
    backgroundColor: 'fff',
    marginTop: 20,
  },
  activePil: {
    backgroundColor: '#fff',
    borderBottomColor: '#000',
    borderBottomWidth: 2,
    alignItems: 'center',
    paddingTop: 10,
    flex: 2,
    marginRight: 5,
  },
  pil: {
    backgroundColor: 'trans',
    alignItems: 'center',
    paddingTop: 10,
    flex: 2,
    borderRadius: 5,
    marginRight: 5,
  },
  row: {
    flexDirection: 'row',
  },
  rowImageContainer: {
    flex: 0.9,
    padding: 20,
    paddingRight: 0,
    paddingBottom: 0,
  },
  rigthCard: {
    flex: 3,
    paddingTop: 30,
    paddingRight: 20,
  },
};
